app_name = "asset_tools"
app_title = "Asset Tools"
app_publisher = "Max Auto Cables Pvt Ltd"
app_description = "Asset QR label printing and utilities"
app_email = "info@maxautocables.com"
app_license = "MIT"
